SELECT
    NAME
  , POPULATION
  , REGION_ID
  , SUM(POPULATION) OVER(ORDER BY REGION_ID ASC) AS REGION_POPULATION
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , POPULATION
  , REGION_ID
  , SUB_REGION_ID
  , SUM(POPULATION) OVER(ORDER BY REGION_ID, SUB_REGION_ID ASC) AS SUB_REGION_POPULATION
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , POPULATION
  , REGION_ID
  , SUB_REGION_ID
  , SUM(POPULATION) OVER(PARTITION BY REGION_ID ORDER BY SUB_REGION_ID DESC) AS SUB_REGION_POPULATION
FROM
    EBA_COUNTRIES;
