SELECT
    NAME
  , REGION_ID
  , SUB_REGION_ID
  , POPULATION
  , SUM(POPULATION) OVER (PARTITION BY REGION_ID ORDER BY SUB_REGION_ID RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS REGION_POPULATION
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , REGION_ID
  , SUB_REGION_ID
  , POPULATION
  , SUM(POPULATION) OVER (PARTITION BY REGION_ID ORDER BY SUB_REGION_ID RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING)  AS REGION_POPULATION
  , SUM(POPULATION) OVER (PARTITION BY REGION_ID ORDER BY SUB_REGION_ID RANGE BETWEEN 0 PRECEDING AND 70 FOLLOWING) AS REGION_POPULATION_PCT
FROM
    EBA_COUNTRIES;
