SELECT
    NAME
  , REGION_ID
  , SUB_REGION_ID
  , POPULATION
  , SUM(POPULATION) OVER (PARTITION BY REGION_ID ORDER BY SUB_REGION_ID)    AS REGION_POPULATION
  , SUM(POPULATION) OVER (PARTITION BY REGION_ID)                           AS SUB_REGION_POPULATION
FROM
    EBA_COUNTRIES;
