SELECT
    NAME
  , POPULATION
  , PERCENT_RANK() OVER(ORDER BY POPULATION)
  , CUME_DIST() OVER(ORDER BY POPULATION)
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , REGION_ID
  , POPULATION
  , PERCENT_RANK() OVER(PARTITION BY REGION_ID ORDER BY POPULATION)
  , CUME_DIST() OVER(PARTITION BY REGION_ID ORDER BY POPULATION)
FROM
    EBA_COUNTRIES;