/*
Query the EBA_COUNTRIES table to return values for the total population grouped by SUB_REGION and ORGANIZATION_REGION_ID,
ensure all null value ID’s are populated with 0 instead of null.

I would like you to show the sub totals for the following combinations only:
SUB_REGION_ID and ORGANIZATION_REGION ID,
SUB_REGION_ID,
GRAND TOTAL
*/
-- My Solution:
SELECT
    NVL(SUB_REGION_ID, 'TOTAL')    AS SUB_REGION_ID,
    NVL(ORGANIZATION_REGION_ID, 0) AS ORGANIZATION_REGION_ID,
    SUM(POPULATION)                AS TOTAL_POPULATION
FROM
    EBA_COUNTRIES
GROUP BY
    ROLLUP (SUB_REGION_ID, ORGANIZATION_REGION_ID)
HAVING
    (SUB_REGION_ID IS NOT NULL AND ORGANIZATION_REGION_ID IS NOT NULL) OR
    (SUB_REGION_ID IS NOT NULL AND ORGANIZATION_REGION_ID IS NULL) OR
    (SUB_REGION_ID IS NULL AND ORGANIZATION_REGION_ID IS NULL)
ORDER BY
    SUB_REGION_ID,
    ORGANIZATION_REGION_ID;

-- Solution Teacher:
SELECT
    NVL(SUB_REGION_ID, 0)
  , NVL(ORGANIZATION_REGION_ID, 0)
  , SUM(POPULATION)
FROM
    EBA_COUNTRIES
GROUP BY
    ROLLUP (NVL(SUB_REGION_ID, 0), NVL(ORGANIZATION_REGION_ID, 0));