SELECT
    *
FROM
    ORDERS;

CREATE VIEW V_ORDERS AS
(
SELECT A.*
     , D.ORDER_TOTAL
FROM ORDER AS A
         LEFT JOIN (SELECT ORDER_ID,
                           SUM(UNIT_PRICE * QUANTITY) AS ORDER_TOTAL
                    FROM ORDER_ITEMS
                    GROUP BY ORDER_ID) AS D
                   ON
                       A.ORDER_ID = D.ORDER_ID;
WHERE
    A.ORDER_STATUS = 'COMPLETE'
);


SELECT
    *
FROM
    ORDER;


-- Solution Teacher
CREATE VIEW V_ORDERS AS
(SELECT A.*, B.ORDER_TOTAL
FROM V_ORDERS AS A
LEFT JOIN
(SELECT ORDER_ID, SUM(UNIT_PRICE * QUANTITY) AS ORDER_TOTAL
FROM ORDER_ITEMS
GROUP BY ORDER_ID) AS B
ON A.ORDER_ID = B.ORDER_ID)
WHERE A.ORDER_STATUS = 'COMPLETE');
