/*
Flag all countries that are in the top 10 percentile for their region in terms of population
*/
SELECT
    NAME
  , REGION_ID
  , POPULATION
  , PERCENT_RANK() OVER(PARTITION BY REGION_ID ORDER BY POPULATION DESC) AS POPULATION_PERCENT_RANK
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , REGION_ID
  , POPULATION
  , PERCENT_RANK() OVER(PARTITION BY REGION_ID ORDER BY POPULATION DESC) AS POPULATION_PERCENT_RANK
  , CASE
        WHEN PERCENT_RANK() OVER(PARTITION BY REGION_ID ORDER BY POPULATION DESC) <= 0.1 THEN 1
        ELSE 0
    END AS POPULATION_PERCENT_RANK_FLAG
FROM
    EBA_COUNTRIES;