/*
Order the countries by population in ascending order and create a running total field for the population
*/
SELECT
    NAME
  , POPULATION
  , SUM(POPULATION) OVER(ORDER BY POPULATION ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_TOTAL_POPULATION
FROM
    EBA_COUNTRIES;


SELECT
    NAME
  , POPULATION
  , SUM(POPULATION) OVER(ORDER BY POPULATION ASC ROWS UNBOUNDED PRECEDING) AS RUNNING_TOTAL_POPULATION
FROM
    EBA_COUNTRIES;